version: '3'
services:
  app:
    image: tobi312/maven-mysql-phpmyadmin
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: myapp
      MYSQL_PASSWORD: myapp
      MYSQL_ROOT_PASSWORD: myapp
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: myapp
    ports:
      - 8080:80
    depends_on:
      - db