---
- name: Install java and net-tools
  hosts: nexusserver
  tasks:
    - name: update apt repository and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install Java v8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools
#        pkg:
#          - openjdk-8-jre-headless
#          - net-tools
- name: Download and unpack Nexus Installer
  hosts: nexusserver
  tasks:
    - name: Check  nexus folder stat exists
      stat:
        path: /opt/nexus
      register: stat_result
    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - debug: msg={{download_result}}
    - name: Untar nexus
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes #true if we want it to be stored on remote serve
      when: not stat_result.stat.exists #only execute unarchive if not exist /opt/nexus folder #Applies to a single task
    - name: find nexus folder
      find:
        paths: /opt
        pattern: "nexus-*"
        file_type: directory
      register: find_result
    - debug: msg={{find_result}}
    - debug: msg={{stat_result.stat.exists}}
    - name: Rename nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists #only execute unarchive if not exist /opt/nexus folder #Applies to a single task

- name: Create nexus user to own nexus folders
  hosts: nexusserver
  tasks:
    - name: Ensure group nexus isexists
      group:
        name: nexus
        state: present
    - name: Create nexus user
      user:
        name: nexus
        group: nexus
    - name: Make nexus user owner of nexus folder
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Make nexus user owner of sonatype-work folder
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse : yes

- name: Start nexus with nexus user
  hosts: nexusserver
  become: true #must ot execute command as root user i.e su - nexus
  become_user: nexus # must become user before executing command
  tasks:
    - name: Set run_as_user nexus
      lineinfile:
        regexp: '^#runs_as_user=""'
        path: /opt/nexus/bin/nexus.rc
        line: runs_as_user="nexus"
#      block-infile: #to change content of a file
#        path: /opt/nexus/bin/nexus.rc
#        block: |
#          runs_as_user="nexus"
    - name: Start nexus
      command: /opt/nexus/bin/nexus start

- name: Ensure nexus is running
  hosts: nexusserver
  tasks:
    - name: Check with ps
      shell: ps aux | grep nexus
      register: nexus_status
    - debug: msg={{nexus_status.stdout_lines}}
    - name: Wait a minute
      pause:
        minutes: 1
    - name: Check with netstat
      shell: netstat -plnt
      register: nexus_status
    - debug: msg={{nexus_status.stdout_lines}}